# spring.application.name=demo
# כתובת החיבור לבסיס הנתונים (MySQL רץ בדרך כלל על פורט 3306)
spring.datasource.url=jdbc:mysql://localhost:3306/fullstack_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Omeriko#1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# הגדרות JPA - יצירה או עדכון אוטומטי של הטבלאות בהתאם לקוד שנכתוב בהמשך
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect